routes/web.php
<?php

Route::group(['middleware' => 'web'], function() {

    Route::get('/', 'HomeController@index')->name('home');
	Route::get('/home', 'HomeController@index')->name('home');
	
	// Just For Administrator
	Route::group(['middleware' => ['ceklevel:1', 'ceklevel:2']], function() {
		
		Route::get('students/certificates', 'StudentController@certificate')->name('students.certificate');
		Route::get('students/certificate/{id}', 'StudentController@set_certificate')->name('students.set_certificate');
		Route::put('students/certificate/{id}', 'StudentController@update_certificate')->name('students.update_certificate');
		Route::get('students/print/ktm/{id}', 'StudentController@printKTM')->name('students.print_ktm');
		Route::get('students/print/ktm', 'StudentController@show_KTM')->name('students.ktm');
		Route::resource('/students', 'StudentController');

		Route::resource('/curriculums', 'CurriculumController');
		Route::resource('/departments', 'DepartmentController');
		Route::resource('/rooms', 'RoomController');
		Route::resource('/lecturers', 'LecturerController');
		Route::resource('/courses', 'CourseController');
		Route::resource('/schedules', 'ScheduleController');
		Route::resource('/years', 'YearController');

		Route::get('/users/profile', 'UserController@profile');
		Route::put('/users/profile/{id}', 'UserController@change_profile')->name('profile.update');
		Route::resource('/users', 'UserController');

		Route::get('/grades', 'GradeController@index')->name('grades.index');
		Route::post('/grades', 'GradeController@store')->name('grades.store');
		Route::get('/grades/{id}/edit', 'GradeController@edit')->name('grades.edit');
		Route::get('/grades/student/{set_nilai}/edit', 'GradeController@set_nilai')->name('grades.set_nilai');
	});


	// Just For Students
	Route::group(['middleware' => 'ceklevel:3'], function() {
		Route::get('/user/student/profile', 'StudentController@detail')->name('students.detail');
	    Route::get('/user/student/profile/edit', 'StudentController@edit_profile')->name('students.edit_profile');
	    Route::put('/students/{student}', 'StudentController@update')->name('students.update');
		
		Route::get('/user/student/password/edit', 'UserController@edit_password')->name('users.edit_password');
		Route::put('/users/{user}', 'UserController@update')->name('users.update');

		Route::get('/user/student/krs', 'KRSController@index')->name('krs.index');
		Route::post('/user/student/krs', 'KRSController@update_krs')->name('krs.update_krs');
		Route::get('/user/student/krs/detail', 'KRSController@detail')->name('krs.detail');
		Route::get('/user/student/krs/detail/print', 'KRSController@print')->name('krs.print');

		Route::get('/user/student/khs', 'KHSController@index')->name('khs.index');
		Route::get('/user/student/khs/detail/print', 'KHSController@print')->name('khs.print');
		Route::post('/user/student/khs', 'KHSController@store')->name('khs.store');

		Route::get('/user/student/biodata', 'DetailController@biodata')->name('detail.biodata');
		Route::get('/user/student/address', 'DetailController@address')->name('detail.address');
		Route::get('/user/student/family', 'DetailController@family')->name('detail.family');
		Route::get('/user/student/uploads', 'DetailController@upload')->name('detail.upload');
		Route::get('/user/student/guardian', 'DetailController@guardian')->name('detail.guardian');
	});
	
	// Just For Lectures
	Route::group(['middleware' => 'ceklevel:4'], function() {
	   	Route::get('/user/lecturer/profile', 'LecturerController@detail')->name('lecturers.detail');
	    Route::get('/user/lecturer/profile/edit', 'LecturerController@edit_profile')->name('lecturers.edit_profile');
	    Route::put('/lecturers/{lecturer}', 'LecturerController@update')->name('lecturers.update');
		
		Route::get('/user/lecturer/password/edit', 'UserController@edit_password')->name('users.edit_password');
		Route::put('/users/{user}', 'UserController@update')->name('users.update');

		Route::resource('/schedules', 'ScheduleController');
		
		Route::get('/grades', 'GradeController@index')->name('grades.index');
		Route::post('/grades', 'GradeController@store')->name('grades.store');
		Route::put('/grades/{grade}', 'GradeController@update_now')->name('grades.update_now');
		Route::get('/grades/{id}/edit', 'GradeController@edit')->name('grades.edit');
		Route::get('/grades/student/{set_nilai}/edit', 'GradeController@set_nilai')->name('grades.set_nilai');
		Route::get('/grades/student/{update_nilai}/edit/nilai', 'GradeController@update_nilai')->name('grades.update_nilai');
	});
	
});

Auth::routes();

app/Year.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Year extends Model
{
    protected $guarded = ['_token', '_method'];
}

app/Http/Controllers/YearController.php
<?php

namespace App\Http\Controllers;

use App\Year;
use Illuminate\Http\Request;

class YearController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $years = Year::orderBy('tahun', 'asc')->get();
        return view('years.index', compact('years'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('years.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Year::create($request->all());
        return redirect(url('/years'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Year $year)
    {
        return view('years.edit', compact('year'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Year $year)
    {
        $year->update($request->all());
        return redirect(url('/years'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Year $year)
    {
        $year->delete();
        return redirect(url('/years'));
    }
}

resources/views/years/create.blade.php
@extends('layouts.master')

@section('content')
<div class="page-inner mt-2">
    <div class="col-12">
        @card
            @slot('title')
                Tambah Data Tahun Akademik
            @endslot
            
            <form method="post" action="{{ route('years.store') }}">
                @csrf
                <div class="form-group row">
                    <label for="tahun" class="col-sm-2 col-form-label">Tahun Akademik</label>
                    <div class="col-sm-8">
                        <div class="d-none">
                            @php 
                            $date = date('Y');
                            $date1 = $date+1;
                            @endphp
                        </div>
                        <input type="text" class="form-control" id="tahun" name="tahun" placeholder="{{ $date }}/{{ $date1 }}" required>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-sm-6 offset-sm-3">
                            <button class="btn btn-primary"> <i class="far fa-save"></i> Simpan</button>
                            <a href="{{ url('/years') }}" class="btn btn-danger ml-3"><i class="fas fa-arrow-circle-left"></i> Kembali</a>
                        </div>                                      
                    </div>
                </div>
            </form>
        @endcard
    </div>
</div>
@endsection

@push('scripts')
<script>
    $(function() {
        $('#datepicker').datetimepicker({
            format: 'MM/DD/YYYY',
        });
    })

    $('label.col-sm-2').addClass('offset-sm-1')
    $('label.offset-sm-1').append(` <span class="required-label">*</span>`)
    $('.form-group .form-control').addClass('form-control-sm')

    // $("form[0]").validate({
    //     rules: {
    //         confirmpassword: {
    //             equalTo: "#password"
    //         }
    //     },
    //     highlight: function(element) {
    //         $(element).closest('.form-group').removeClass('has-success').addClass('has-error');
    //     },
    //     success: function(element) {
    //         $(element).closest('.form-group').removeClass('has-error').addClass('has-success');
    //     },
    // });
</script>
@endpush

resources/views/years/edit.blade.php
@extends('layouts.master')

@section('content')
<div class="page-inner mt-2">
    <div class="col-12">
        @card
            @slot('title')
                Edit Data Tahun Akademik
            @endslot
            
            <form method="post" action="{{ route('years.update', $year->id) }}">
                @csrf @method('put')
                <div class="form-group row">
                    <label for="tahun" class="col-sm-2 col-form-label">Tahun Akademik</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" id="tahun" name="tahun" required value="{{ $year->tahun }}">
                    </div>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-sm-6 offset-sm-3">
                            <button class="btn btn-primary"> <i class="far fa-save"></i> Simpan</button>
                            <a href="{{ url('/years') }}" class="btn btn-danger ml-3"><i class="fas fa-arrow-circle-left"></i> Kembali</a>
                        </div>                                      
                    </div>
                </div>
            </form>
        @endcard
    </div>
</div>
@endsection

@push('scripts')
<script>
    $('label.col-sm-2').addClass('offset-sm-1')
    $('label.offset-sm-1').append(` <span class="required-label">*</span>`)
    $('.form-group .form-control').addClass('form-control-sm')
</script>
@endpush

resources/views/years/index.blade.php
@extends('layouts.master')

@section('content')
<div class="panel-header bg-primary-gradient">
    <div class="page-inner py-5">
        <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
            <div>
                <h2 class="text-white pb-2 fw-bold">Tahun Akademik</h2>
            </div>
            <div class="ml-md-auto py-2 py-md-0">
                <a href="{{ route('years.create') }}" class="btn btn-white btn-sm btn-border"><i class="fas fa-plus-circle"></i> Tambah</a>
            </div>
        </div>
    </div>
</div>

<div class="page-inner mt--5">
    <div class="row mt--2">
        <div class="col-12">
            @card
                @slot('title')
                    
                @endslot

                @table
                    @slot('thead')
                        <th>No</th>
                        <th>Tahun Akademik</th>
                        <th>Aksi</th>
                    @endslot
                    
                    @php $no = 1; @endphp
                    @foreach ($years as $curriculum)
                        <tr>
                            <td width="5%">{{ $no++ }}.</td>
                            <td>{{ $curriculum->tahun }}</td>
                            <td width="5%">
                                <form method="POST" action="{{ route('years.destroy', $curriculum->id) }}">
                                    @csrf @method('delete')
                                    <div class="form-button-action text-center">
                                        <a href="{{ route('years.edit', $curriculum->id) }}" class="btn btn-link btn-primary" title="Edit"><i class="far fa-edit"></i></a>
                                        <button class="btn btn-link btn-danger" title="Delete" onclick="return confirm('Yakin?')"><i class="fas fa-trash-alt"></i></button>
                                    </div>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                @endtable
            @endcard
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
    $('.table').DataTable({
        "language": {
            "zeroRecords": "<strong>Data tidak ditemukan</strong>"
        }
    })

    $('.card-header').addClass('d-none')
</script>
@endpush