routes/web.php
<?php

Route::group(['middleware' => 'web'], function() {

    Route::get('/', 'HomeController@index')->name('home');
	Route::get('/home', 'HomeController@index')->name('home');
	
	// Just For Administrator
	Route::group(['middleware' => ['ceklevel:1', 'ceklevel:2']], function() {
		
		Route::get('students/certificates', 'StudentController@certificate')->name('students.certificate');
		Route::get('students/certificate/{id}', 'StudentController@set_certificate')->name('students.set_certificate');
		Route::put('students/certificate/{id}', 'StudentController@update_certificate')->name('students.update_certificate');
		Route::get('students/print/ktm/{id}', 'StudentController@printKTM')->name('students.print_ktm');
		Route::get('students/print/ktm', 'StudentController@show_KTM')->name('students.ktm');
		Route::resource('/students', 'StudentController');

		Route::resource('/curriculums', 'CurriculumController');
		Route::resource('/departments', 'DepartmentController');
		Route::resource('/rooms', 'RoomController');
		Route::resource('/lecturers', 'LecturerController');
		Route::resource('/courses', 'CourseController');
		Route::resource('/schedules', 'ScheduleController');
		Route::resource('/years', 'YearController');

		Route::get('/users/profile', 'UserController@profile');
		Route::put('/users/profile/{id}', 'UserController@change_profile')->name('profile.update');
		Route::resource('/users', 'UserController');

		Route::get('/grades', 'GradeController@index')->name('grades.index');
		Route::post('/grades', 'GradeController@store')->name('grades.store');
		Route::get('/grades/{id}/edit', 'GradeController@edit')->name('grades.edit');
		Route::get('/grades/student/{set_nilai}/edit', 'GradeController@set_nilai')->name('grades.set_nilai');
	});


	// Just For Students
	Route::group(['middleware' => 'ceklevel:3'], function() {
		Route::get('/user/student/profile', 'StudentController@detail')->name('students.detail');
	    Route::get('/user/student/profile/edit', 'StudentController@edit_profile')->name('students.edit_profile');
	    Route::put('/students/{student}', 'StudentController@update')->name('students.update');
		
		Route::get('/user/student/password/edit', 'UserController@edit_password')->name('users.edit_password');
		Route::put('/users/{user}', 'UserController@update')->name('users.update');

		Route::get('/user/student/krs', 'KRSController@index')->name('krs.index');
		Route::post('/user/student/krs', 'KRSController@update_krs')->name('krs.update_krs');
		Route::get('/user/student/krs/detail', 'KRSController@detail')->name('krs.detail');
		Route::get('/user/student/krs/detail/print', 'KRSController@print')->name('krs.print');

		Route::get('/user/student/khs', 'KHSController@index')->name('khs.index');
		Route::get('/user/student/khs/detail/print', 'KHSController@print')->name('khs.print');
		Route::post('/user/student/khs', 'KHSController@store')->name('khs.store');

		Route::get('/user/student/biodata', 'DetailController@biodata')->name('detail.biodata');
		Route::get('/user/student/address', 'DetailController@address')->name('detail.address');
		Route::get('/user/student/family', 'DetailController@family')->name('detail.family');
		Route::get('/user/student/uploads', 'DetailController@upload')->name('detail.upload');
		Route::get('/user/student/guardian', 'DetailController@guardian')->name('detail.guardian');
	});
	
	// Just For Lectures
	Route::group(['middleware' => 'ceklevel:4'], function() {
	   	Route::get('/user/lecturer/profile', 'LecturerController@detail')->name('lecturers.detail');
	    Route::get('/user/lecturer/profile/edit', 'LecturerController@edit_profile')->name('lecturers.edit_profile');
	    Route::put('/lecturers/{lecturer}', 'LecturerController@update')->name('lecturers.update');
		
		Route::get('/user/lecturer/password/edit', 'UserController@edit_password')->name('users.edit_password');
		Route::put('/users/{user}', 'UserController@update')->name('users.update');

		Route::resource('/schedules', 'ScheduleController');
		
		Route::get('/grades', 'GradeController@index')->name('grades.index');
		Route::post('/grades', 'GradeController@store')->name('grades.store');
		Route::put('/grades/{grade}', 'GradeController@update_now')->name('grades.update_now');
		Route::get('/grades/{id}/edit', 'GradeController@edit')->name('grades.edit');
		Route::get('/grades/student/{set_nilai}/edit', 'GradeController@set_nilai')->name('grades.set_nilai');
		Route::get('/grades/student/{update_nilai}/edit/nilai', 'GradeController@update_nilai')->name('grades.update_nilai');
	});
	
});

Auth::routes();

app/Lecturer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Lecturer extends Model
{
    protected $guarded = ['_token', '_method'];

	public function getCreatedAtAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d F Y');
    }
}

app/Http/Controllers/LecturerController.php
<?php

namespace App\Http\Controllers;

use App\Lecturer;
use Illuminate\Http\Request;
use App\Department;
use File;

class LecturerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lecturers = Lecturer::latest()->get();
        return view('lecturers.index', compact('lecturers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('lecturers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $foto = null;
        if ($request->hasFile('foto')) {
            $foto = $this->saveFile($request->nama, $request->file('foto'));
        }

        $lecturers = Lecturer::create([
            'kode' => $request->kode,
            'nidn' => $request->nidn,
            'nama' => $request->nama,
            'pend_s1' => $request->pend_s1,
            'pend_s2' => $request->pend_s2,
            'pend_s3' => $request->pend_s3,
            'alamat' => $request->alamat,
            'telpon' => $request->telpon,
            'email' => $request->email,
            'foto' => $foto,
        ]);

        $user = \Auth::user()->create([
            'name' => $request->nama,
            'email' => $request->email,
            'user_id' => $request->nidn,
            'password' => bcrypt($request['password']),
            'image' => $foto,
            'role_id' => 4
        ]);

        return redirect(url('/lecturers'));
    }

    private function saveFile($name, $photo)
    {
        $images = str_slug($name) . time() .'.' . $photo->getClientOriginalExtension();
        $photo->move(public_path('assets/img/uploads'), $images);
        return $images;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function show(Lecturer $lecturer)
    {
        return view('lecturers.detail', compact('lecturer'));
    }

    public function detail()
    {
        $lecturer = Lecturer::where('nidn', \Auth::user()->user_id)->first();
        $departments = Department::all();
        return view('lecturers.detail', compact('lecturer', 'departments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function edit(Lecturer $lecturer)
    {
        return view('lecturers.edit', compact('lecturer'));
    }

    public function edit_profile()
    {
        $lecturer = Lecturer::where('nidn', \Auth::user()->user_id)->first();
        $departments = Department::all();
        return view('lecturers.edit', compact('lecturer', 'departments'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Lecturer $lecturer)
    {
        $foto = $lecturer->foto;
        if ($request->hasFile('foto')) {
            !empty($foto) ? File::delete(public_path('assets/img/uploads/' . $foto)) : null;
            $foto = $this->saveFile($request->nama, $request->file('foto'));
        }

        $lecturer->update([
            'kode' => $request->kode,
            'nidn' => $request->nidn,
            'nama' => $request->nama,
            'pend_s1' => $request->pend_s1,
            'pend_s2' => $request->pend_s2,
            'pend_s3' => $request->pend_s3,
            'alamat' => $request->alamat,
            'telpon' => $request->telpon,
            'email' => $request->email,
            'foto' => $foto,
        ]);

        $user = \Auth::user()->where('user_id', $lecturer->nidn)->update([
            'name' => $request->nama,
            'image' => $foto,
        ]);

        if(\Auth::user()->role_id == 4) return redirect(url('/user/lecturer/profile'));
        else return redirect(url('/lecturers'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy(Lecturer $lecturer)
    {
        $lecturer->delete();
        return redirect()->back();
    }
}

resources/views/lecturers/create.blade.php
@extends('layouts.master')

@section('content')
<div class="page-inner mt-2">
    <div class="col-12">
        @card
            @slot('title')
                Tambah Data Dosen
            @endslot
            
            <form method="post" action="{{ route('lecturers.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="form-group row">
                    <label for="kode" class="col-sm-2 col-form-label">Kode Dosen</label>
                    <div class="col-sm-2">
                        <input class="form-control" name="kode" id="kode" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="nidn" class="col-sm-2 col-form-label">NIDN/NIK</label>
                    <div class="col-sm-4">
                        <input class="form-control" name="nidn" id="nidn" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="nama" class="col-sm-2 col-form-label">Nama</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" id="nama" name="nama" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="pend_s1" class="col-sm-2 col-form-label">Pendidikan S1</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" id="pend_s1" name="pend_s1">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="pend_s2" class="col-sm-2 col-form-label">Pendidikan S2</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" id="pend_s2" name="pend_s2">
                    </div>
                </div><div class="form-group row">
                    <label for="pend_s3" class="col-sm-2 col-form-label">Pendidikan S3</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" id="pend_s3" name="pend_s3">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="alamat" class="col-sm-2 col-form-label">Alamat</label>
                    <div class="col-sm-8">
                        <textarea name="alamat" id="alamat" class="form-control" rows="5"></textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="telpon" class="col-sm-2 col-form-label">No Telpon</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" id="telpon" name="telpon" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="email" class="col-sm-2 col-form-label">Email</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" id="email" name="email" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="password" class="col-sm-2 col-form-label">Password</label>
                    <div class="col-sm-6">
                        <input type="password" class="form-control" id="password" name="password" min="6">
                    </div>
                </div>
                <div class="form-group  row">
                    <label class="col-sm-2">Upload Image</label>
                    <div class="col-sm-4">
                        <div class="input-file input-file-image mt--3">
                            <input type="file" class="form-control form-control-file" id="foto" name="foto" accept="image/*" required >
                            <label for="foto" class="img-circle" style="cursor: pointer;"><i class="fa fa-file-image"></i>
                                <img class="img-upload-preview rounded" height="200" src="http://placehold.it/200x200" alt="preview">
                            </label>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-sm-6 offset-sm-3">
                            <button class="btn btn-primary"> <i class="far fa-save"></i> Simpan</button>
                            <a href="{{ url('/lecturers') }}" class="btn btn-danger ml-3"><i class="fas fa-arrow-circle-left"></i> Kembali</a>
                        </div>                                      
                    </div>
                </div>
            </form>
        @endcard
    </div>
</div>
@endsection

@push('scripts')
<script>
    $(function() {
        $('#datepicker').datetimepicker({
            format: 'MM/DD/YYYY',
        });
    })

    $('label.col-sm-2').addClass('offset-sm-1')
    $('label.offset-sm-1').append(` <span class="required-label">*</span>`)
    $('.form-group .form-control').addClass('form-control-sm')
</script>
@endpush

resources/views/lecturers/detail.blade.php
@extends('layouts.master')

@section('content')
<div class="page-inner mt-2">
    <div class="col-12">
        @card
            @slot('title')
                Detail Dosen
            @endslot

            <div class="card mb-3">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img src="{{ asset('/assets/img/uploads/') }}/{{ $lecturer->foto }}" class="card-img" alt="">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body mt--3">
                            <table width="50%" class="table table-bordered">
                                <tr>
                                    <td>Nama</td>
                                    <td>: {{ ucfirst($lecturer->nama) }}</td>
                                </tr>
                                <tr>
                                    <td>No Telpon</td>
                                    <td>: {{ $lecturer->telpon }}</td>
                                </tr>
                                <tr>
                                    <td>Email</td>
                                    <td>: {{ $lecturer->email }}</td>
                                </tr>
                                <tr>
                                    <td>Kode Dosen</td>
                                    <td>: {{ $lecturer->kode }}</td>
                                </tr>
                                <tr>
                                    <td>NIDN / NIK</td>
                                    <td>: {{ $lecturer->nidn }}</td>
                                </tr>
                                <tr>
                                    <td>S1</td>
                                    <td>: {{ $lecturer->pend_s1 }}</td>
                                </tr>
                                <tr>
                                    <td>S2</td>
                                    <td>: {{ $lecturer->pend_s2 }}</td>
                                </tr>
                                <tr>
                                    <td>S3</td>
                                    <td>: {{ $lecturer->pend_s3 }}</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="row">
                <a href="{{ url('/lecturers') }}" class="btn btn-danger ml-3"><i class="fas fa-arrow-circle-left"></i> Kembali</a>
            </div>
        @endcard
    </div>
</div>
@endsection

@push('scripts')
<script>
    $('.profile').parent().addClass('active');
</script>
@endpush

resources/views/lecturers/edit.blade.php
@extends('layouts.master')

@section('content')
<div class="page-inner mt-2">
    <div class="col-12">
        @card
            @slot('title')
            @if (Auth::user()->role_id == 1 || Auth::user()->role_id == 2)
                Edit Data Dosen
            @else
                Edit Profile
            @endif
            @endslot
            
            <form method="post" action="{{ route('lecturers.update', $lecturer->id) }}" enctype="multipart/form-data">
                @csrf @method('put')
                <div class="form-group row">
                    <label for="kode" class="col-sm-2 col-form-label">Kode Dosen</label>
                    <div class="col-sm-2">
                        <input class="form-control" name="kode" id="kode" required value="{{ $lecturer->kode }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="nidn" class="col-sm-2 col-form-label">NIDN/NIK</label>
                    <div class="col-sm-4">
                        <input class="form-control" name="nidn" id="nidn" required value="{{ $lecturer->nidn }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="nama" class="col-sm-2 col-form-label">Nama</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" id="nama" name="nama" required value="{{ $lecturer->nama }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="pend_s1" class="col-sm-2 col-form-label">Pendidikan S1</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" id="pend_s1" name="pend_s1" value="{{ $lecturer->pend_s1 }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="pend_s2" class="col-sm-2 col-form-label">Pendidikan S2</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" id="pend_s2" name="pend_s2" value="{{ $lecturer->pend_s2 }}">
                    </div>
                </div><div class="form-group row">
                    <label for="pend_s3" class="col-sm-2 col-form-label">Pendidikan S3</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" id="pend_s3" name="pend_s3" value="{{ $lecturer->pend_s3 }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="alamat" class="col-sm-2 col-form-label">Alamat</label>
                    <div class="col-sm-8">
                        <textarea name="alamat" id="alamat" class="form-control" rows="5">{{ $lecturer->alamat }}</textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="telpon" class="col-sm-2 col-form-label">No Telpon</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" id="telpon" name="telpon" required value="{{ $lecturer->telpon }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="email" class="col-sm-2 col-form-label">Email</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" id="email" name="email" required value="{{ $lecturer->email }}">
                    </div>
                </div>
                <div class="form-group  row">
                    <label class="col-sm-2">Upload Image</label>
                    <div class="col-sm-4">
                        <div class="input-file input-file-image mt--3">
                            <input type="file" class="form-control form-control-file" id="foto" name="foto" accept="image/*" value="{{ $lecturer->foto }}">
                            <label for="foto" class="img-circle" style="cursor: pointer;"><i class="fa fa-file-image"></i>
                                <img class="img-upload-preview rounded" height="200" src="{{ asset('assets/img/uploads/') }}/{{ $lecturer->foto }}" alt="preview">
                            </label>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-sm-6 offset-sm-3">
                            <button class="btn btn-primary"> <i class="far fa-save"></i> Simpan</button>
                            <a href="{{ url('/lecturers') }}" class="btn btn-danger ml-3"><i class="fas fa-arrow-circle-left"></i> Kembali</a>
                        </div>                                      
                    </div>
                </div>
            </form>
        @endcard
    </div>
</div>
@endsection

@push('scripts')
<script>
    $('.profile').parent().addClass('active');
    $('#nidn, #email, #kode').attr('readonly', true)

    $('label.col-sm-2').addClass('offset-sm-1')
    $('label.offset-sm-1').append(` <span class="required-label">*</span>`)
    $('.form-group .form-control').addClass('form-control-sm')
</script>
@endpush

resources/views/lecturers/index.blade.php
@extends('layouts.master')

@section('content')
<div class="panel-header bg-primary-gradient">
    <div class="page-inner py-5">
        <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
            <div>
                <h2 class="text-white pb-2 fw-bold">Daftar Dosen</h2>
            </div>
            <div class="ml-md-auto py-2 py-md-0">
                <a href="{{ route('lecturers.create') }}" class="btn btn-white btn-sm btn-border"><i class="fas fa-plus-circle"></i> Tambah</a>
            </div>
        </div>
    </div>
</div>

<div class="page-inner mt--5">
    <div class="row mt--2">
        <div class="col-12">
            @card
                @slot('title')
                    
                @endslot

                @table
                    @slot('thead')
                        <th>No</th>
                        <th>Kode Dosen</th>
                        <th>Nama</th>
                        <th>Telpon</th>
                        <th>Email</th>
                        <th>Alamat</th>
                        <th>Foto</th>
                        <th>Aksi</th>
                    @endslot
                    
                    @php $no = 1; @endphp
                    @foreach ($lecturers as $lecturer)
                        <tr>
                            <td width="5%">{{ $no++ }}.</td>
                            <td width="15%">{{ $lecturer->kode }}</td>
                            <td width="25%">{{ $lecturer->nama }}</td>
                            <td>{{ $lecturer->telpon }}</td>
                            <td>{{ $lecturer->email }}</td>
                            <td>{{ $lecturer->alamat }}</td>
                            <td>
                                <img src="{{ asset('assets/img/uploads/') }}/{{ $lecturer->foto }}" alt="profile dosen" class="rounded-circle" height="30">
                            </td>
                            <td width="5%">
                                <form method="POST" action="{{ route('lecturers.destroy', $lecturer->id) }}">
                                    @csrf @method('delete')
                                    <div class="form-button-action text-center">
                                        <a href="{{ route('lecturers.edit', $lecturer->id) }}" class="btn btn-link btn-primary" title="Edit"><i class="far fa-edit"></i></a>
                                        <button class="btn btn-link btn-danger" title="Delete" onclick="return confirm('Yakin?')"><i class="fas fa-trash-alt"></i></button>
                                        <a href="{{ route('lecturers.show', $lecturer->id) }}" class="btn btn-link btn-default" title="Detail"><i class="fas fa-search-plus"></i></a>
                                    </div>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                @endtable
            @endcard
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
    $('.table').DataTable({
        "language": {
            "zeroRecords": "<strong>Data tidak ditemukan</strong>"
        }
    })

    $('.card-header').addClass('d-none')
    $('.table').addClass('table-responsive')
</script>
@endpush