routes/web.php
<?php

Route::group(['middleware' => 'web'], function() {

    Route::get('/', 'HomeController@index')->name('home');
	Route::get('/home', 'HomeController@index')->name('home');
	
	// Just For Administrator
	Route::group(['middleware' => ['ceklevel:1', 'ceklevel:2']], function() {
		
		Route::get('students/certificates', 'StudentController@certificate')->name('students.certificate');
		Route::get('students/certificate/{id}', 'StudentController@set_certificate')->name('students.set_certificate');
		Route::put('students/certificate/{id}', 'StudentController@update_certificate')->name('students.update_certificate');
		Route::get('students/print/ktm/{id}', 'StudentController@printKTM')->name('students.print_ktm');
		Route::get('students/print/ktm', 'StudentController@show_KTM')->name('students.ktm');
		Route::resource('/students', 'StudentController');

		Route::resource('/curriculums', 'CurriculumController');
		Route::resource('/departments', 'DepartmentController');
		Route::resource('/rooms', 'RoomController');
		Route::resource('/lecturers', 'LecturerController');
		Route::resource('/courses', 'CourseController');
		Route::resource('/schedules', 'ScheduleController');
		Route::resource('/years', 'YearController');

		Route::get('/users/profile', 'UserController@profile');
		Route::put('/users/profile/{id}', 'UserController@change_profile')->name('profile.update');
		Route::resource('/users', 'UserController');

		Route::get('/grades', 'GradeController@index')->name('grades.index');
		Route::post('/grades', 'GradeController@store')->name('grades.store');
		Route::get('/grades/{id}/edit', 'GradeController@edit')->name('grades.edit');
		Route::get('/grades/student/{set_nilai}/edit', 'GradeController@set_nilai')->name('grades.set_nilai');
	});


	// Just For Students
	Route::group(['middleware' => 'ceklevel:3'], function() {
		Route::get('/user/student/profile', 'StudentController@detail')->name('students.detail');
	    Route::get('/user/student/profile/edit', 'StudentController@edit_profile')->name('students.edit_profile');
	    Route::put('/students/{student}', 'StudentController@update')->name('students.update');
		
		Route::get('/user/student/password/edit', 'UserController@edit_password')->name('users.edit_password');
		Route::put('/users/{user}', 'UserController@update')->name('users.update');

		Route::get('/user/student/krs', 'KRSController@index')->name('krs.index');
		Route::post('/user/student/krs', 'KRSController@update_krs')->name('krs.update_krs');
		Route::get('/user/student/krs/detail', 'KRSController@detail')->name('krs.detail');
		Route::get('/user/student/krs/detail/print', 'KRSController@print')->name('krs.print');

		Route::get('/user/student/khs', 'KHSController@index')->name('khs.index');
		Route::get('/user/student/khs/detail/print', 'KHSController@print')->name('khs.print');
		Route::post('/user/student/khs', 'KHSController@store')->name('khs.store');

		Route::get('/user/student/biodata', 'DetailController@biodata')->name('detail.biodata');
		Route::get('/user/student/address', 'DetailController@address')->name('detail.address');
		Route::get('/user/student/family', 'DetailController@family')->name('detail.family');
		Route::get('/user/student/uploads', 'DetailController@upload')->name('detail.upload');
		Route::get('/user/student/guardian', 'DetailController@guardian')->name('detail.guardian');
	});
	
	// Just For Lectures
	Route::group(['middleware' => 'ceklevel:4'], function() {
	   	Route::get('/user/lecturer/profile', 'LecturerController@detail')->name('lecturers.detail');
	    Route::get('/user/lecturer/profile/edit', 'LecturerController@edit_profile')->name('lecturers.edit_profile');
	    Route::put('/lecturers/{lecturer}', 'LecturerController@update')->name('lecturers.update');
		
		Route::get('/user/lecturer/password/edit', 'UserController@edit_password')->name('users.edit_password');
		Route::put('/users/{user}', 'UserController@update')->name('users.update');

		Route::resource('/schedules', 'ScheduleController');
		
		Route::get('/grades', 'GradeController@index')->name('grades.index');
		Route::post('/grades', 'GradeController@store')->name('grades.store');
		Route::put('/grades/{grade}', 'GradeController@update_now')->name('grades.update_now');
		Route::get('/grades/{id}/edit', 'GradeController@edit')->name('grades.edit');
		Route::get('/grades/student/{set_nilai}/edit', 'GradeController@set_nilai')->name('grades.set_nilai');
		Route::get('/grades/student/{update_nilai}/edit/nilai', 'GradeController@update_nilai')->name('grades.update_nilai');
	});
	
});

Auth::routes();

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Student extends Model
{
	protected $guarded = ['_token', '_method'];

	public function getCreatedAtAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d F Y');
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Student;
use App\Department;
use App\Class_time;
use App\User;
use App\KRS;
use Illuminate\Http\Request;
use File;
use PDF;
use DB;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = Student::latest()->get();
        $departments = Department::all();
        return view('students.index', compact('students', 'departments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $departments = Department::all();
        $class_times = Class_time::all();
        return view('students.create', compact('departments', 'class_times'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $foto = null;
        if ($request->hasFile('foto')) {
            $foto = $this->saveFile($request->name, $request->file('foto'));
        }

        $students = Student::create([
            'nim' => $request->nim,
            'nama' => $request->nama,
            'tempat_lahir' => $request->tempat_lahir,
            'tanggal_lahir' => $request->tanggal_lahir,
            'alamat' => $request->alamat,
            'kode_jurusan' => $request->kode_jurusan,
            'semester' => $request->semester,
            'jenis_kelamin' => $request->jenis_kelamin,
            'email' => $request->email,
            'telpon' => $request->telpon,
            'angkatan' => $request->angkatan,
            'foto' => $foto,
            'krs' => 1,
            'khs' => 1,
            'kelas_id' => $request->kelas_id
        ]);

        $user = User::create([
            'name' => $request->nama,
            'email' => $request->email,
            'user_id' => $request->nim,
            'password' => bcrypt($request['password']),
            'image' => $foto,
            'role_id' => 3
        ]);

        return redirect(url('/students'));
    }

    private function saveFile($name, $photo)
    {
        $images = str_slug($name) . time() .'.' . $photo->getClientOriginalExtension();
        $photo->move(public_path('assets/img/uploads'), $images);
        return $images;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function show(Student $student)
    {
        $departments = Department::all();
        return view('students.detail', compact('student', 'departments'));
    }

    public function detail()
    {
        $student = Student::where('nim', \Auth::user()->user_id)->first();
        $departments = Department::all();

        if (\Auth::user()->role_id == 3) {
            return view('__students.detail', compact('student', 'departments'));
        } else return view('students.detail', compact('student', 'departments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function edit(Student $student)
    {
        $departments = Department::all();
        $class_times = Class_time::all();
        return view('students.edit', compact('student', 'departments', 'class_times'));
    }

    public function edit_profile()
    {
        $student = Student::where('nim', \Auth::user()->user_id)->first();
        $departments = Department::all();
        $class_times = Class_time::all();
        return view('__students.edit', compact('student', 'departments', 'class_times'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Student $student)
    {
        $foto = $student->image;
        if ($request->hasFile('foto')) {
            !empty($foto) ? File::delete(public_path('assets/img/uploads/' . $foto)) : null; 
            $foto = $this->saveFile($request->nama, $request->file('foto'));
        }

        $student->update([
            'nim' => $request->nim,
            'nama' => $request->nama,
            'tempat_lahir' => $request->tempat_lahir,
            'tanggal_lahir' => $request->tanggal_lahir,
            'alamat' => $request->alamat,
            'kode_jurusan' => $request->kode_jurusan,
            'semester' => $request->semester,
            'jenis_kelamin' => $request->jenis_kelamin,
            'email' => $request->email,
            'telpon' => $request->telpon,
            'angkatan' => $request->angkatan,
            'foto' => $foto,
            'krs' => 1,
            'khs' => 1,
            'kelas_id' => $request->kelas_id
        ]);

        $user = \Auth::user()->where('user_id', $student->nim)->update([
            'name' => $request->nama,
            'image' => $foto,
        ]);

        if(\Auth::user()->role_id == 3) return redirect(url('/user/student/profile'));
        else return redirect(url('/students'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy(Student $student)
    {
        $student->delete();
        return redirect()->back();
    }

    public function certificate()
    {
        $students = Student::latest()->get();
        return view('certificates.index', compact('students'));
    }

    public function set_certificate($id)
    {
        $student = Student::find($id);
        return view('certificates.edit', compact('student'));
    }

    public function update_certificate(Request $request, $id)
    {
        $student = Student::find($id);
        $student->update([
            'no_ijazah' => $request->no_ijazah,
            'judul_skripsi' => $request->judul_skripsi
        ]);

        return redirect(url('/students/certificates'));
    }

    public function show_KTM()
    {
        $students = Student::all();
        $departments = Department::all();

        return view('students.show_ktm', compact('students', 'departments'));
    }

    public function printKTM($id)
    {
        $student = Student::find($id);
        $departments = Department::all();

        // $pdf = PDF::loadView('students.print_ktm', compact('student', 'departments'));
        // $pdf->setPaper(array(0,0,600,440), 'potrait');
        // return $pdf->stream();

        return view('students.print_ktm', compact('student', 'departments'));
    }

























    // public function Cek()
    // {
    //     $detail = Cek::with('produk')
    //             ->where('id_penjualan', '=', session('idpenjualan'))
    //             ->get();
                
    //     $penjualan = Cek::find(session('idpenjualan'));
    //     $setting = Setting::first();
    //     $no = 0;

    //     $pdf = PDF::loadView('penjualan_detail.notapdf', compact('detail', 'penjualan', 'setting', 'no'));
    //     $pdf->setPaper(array(0,0,609,440), 'potrait');
    //     return $pdf->stream();
    // }
}

resources/views/students/create.blade.php
@extends('layouts.master')

@section('content')
<div class="page-inner mt-2">
    <div class="col-12">
        @card
            @slot('title')
                Tambah Data Mahasiswa
            @endslot
            
            <form method="post" action="{{ route('students.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="form-group row">
                    <label for="nim" class="col-sm-2 col-form-label">NIM</label>
                    <div class="col-sm-6">
                        <input class="form-control" name="nim" id="nim" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="nama" class="col-sm-2 col-form-label">Nama</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" id="nama" name="nama" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="tempat_lahir" class="col-sm-2 col-form-label">Tempat Lahir</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" id="tempat_lahir" name="tempat_lahir" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="datepicker" class="col-sm-2 col-form-label">Tanggal Lahir </label>
                    <div class="col-sm-6">
                        <div class="input-group">
                            <input type="text" class="form-control" id="datepicker" name="tanggal_lahir" required>
                            <div class="input-group-append">
                                <span class="input-group-text">
                                    <i class="fa fa-calendar"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="alamat" class="col-sm-2 col-form-label">Alamat</label>
                    <div class="col-sm-8">
                        <textarea name="alamat" id="alamat" class="form-control" rows="5"></textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="telpon" class="col-sm-2 col-form-label">No Telpon</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" id="telpon" name="telpon" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="angkatan" class="col-sm-2 col-form-label">Tahun Angkatan</label>
                    <div class="col-sm-4">
                        <select name="angkatan" id="angkatan" class="form-control" required>
                            @for ($i = date('Y'); $i >= date('Y') - 10; $i--)
                                <option value="{{ $i }}">{{ $i }}</option>
                            @endfor
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="semester" class="col-sm-2 col-form-label">Semester</label>
                    <div class="col-sm-4">
                        <select name="semester" id="semester" class="form-control" required>
                            @for ($i = 1; $i <= 8; $i++)    
                                <option value="{{ $i }}">{{ $i }}</option>
                            @endfor
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="jurusan" class="col-sm-2 col-form-label">Jurusan</label>
                    <div class="col-sm-6">
                        <select class="form-control" id="jurusan" name="kode_jurusan" required>
                            @foreach ($departments as $department)
                                <option value="{{ $department->kode }}">{{ $department->nama }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="kelas" class="col-sm-2 col-form-label">Kelas</label>
                    <div class="col-sm-6">
                        <select class="form-control" id="kelas" name="kelas_id" required>
                            @foreach ($class_times as $class)
                                <option value="{{ $class->id }}">{{ $class->nama }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="jk" class="col-sm-2 col-form-label">Jenis Kelamin</label>
                    <div class="custom-control custom-radio">
                        <input type="radio" id="laki-laki" name="jenis_kelamin" class="custom-control-input" value="L" required>
                        <label class="custom-control-label" for="laki-laki">Laki-laki</label>
                    </div>
                    <div class="custom-control custom-radio">
                        <input type="radio" id="Perempuan" name="jenis_kelamin" class="custom-control-input" value="P" required>
                        <label class="custom-control-label" for="Perempuan">Perempuan</label>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="email" class="col-sm-2 col-form-label">Email</label>
                    <div class="col-sm-6">
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="password" class="col-sm-2 col-form-label">Password</label>
                    <div class="col-sm-6">
                        <input type="password" class="form-control" id="password" name="password" required minlength="6">
                    </div>
                </div>
                <div class="form-group  row">
                    <label class="col-sm-2">Upload Image</label>
                    <div class="col-sm-4">
                        <div class="input-file input-file-image mt--3">
                            <input type="file" class="form-control form-control-file" id="foto" name="foto" accept="image/*" required >
                            <label for="foto" class="img-circle" style="cursor: pointer;"><i class="fa fa-file-image"></i>
                                <img class="img-upload-preview rounded" height="200" src="http://placehold.it/200x200" alt="preview">
                            </label>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-sm-6 offset-sm-3">
                            <button class="btn btn-primary"> <i class="far fa-save"></i> Simpan</button>
                            <a href="{{ url('/students') }}" class="btn btn-danger ml-3"><i class="fas fa-arrow-circle-left"></i> Kembali</a>
                        </div>                                      
                    </div>
                </div>
            </form>
        @endcard
    </div>
</div>
@endsection

@push('scripts')
<script>
    $(function() {
        $('#datepicker').datetimepicker({
            format: 'MM/DD/YYYY',
        });
    })

    $('label.col-sm-2').addClass('offset-sm-1')
    $('label.offset-sm-1').append(` <span class="required-label">*</span>`)
    $('.form-group .form-control').addClass('form-control-sm')
</script>
@endpush

resources/views/students/detail.blade.php
@extends('layouts.master')

@section('content')
<div class="page-inner mt-2">
    <div class="col-12">
        @card
            @slot('title')
                Detail Mahasiswa
            @endslot

            <div class="card mb-3">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img src="{{ asset('/assets/img/uploads/') }}/{{ $student->foto }}" class="card-img" alt="">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body mt--3">
                            <table width="50%" class="table table-bordered">
                                <tr>
                                    <td>Nama</td>
                                    <td>: {{ ucfirst($student->nama) }}</td>
                                </tr>
                                <tr>
                                    <td>Alamat</td>
                                    <td>: {{ $student->alamat }}</td>
                                </tr>
                                <tr>
                                    <td>Email</td>
                                    <td>: {{ $student->email }}</td>
                                </tr>
                                <tr>
                                    <td>Tanggal Lahir</td>
                                    <td>: {{ date('F d, Y', strtotime($student->tanggal_lahir)) }}</td>
                                </tr>
                                <tr>
                                    <td>Jurusan</td>
                                    <td>: 
                                        @foreach ($departments as $department)
                                            {{ $department->kode == $student->kode_jurusan ? $department->nama : '' }}
                                        @endforeach
                                    </td>
                                </tr>
                                <tr>
                                    <td>NIM</td>
                                    <td>: {{ $student->nim }}</td>
                                </tr>
                                <tr>
                                    <td>Member Pada</td>
                                    <td>: {{ $student->created_at }}</td>
                                </tr>
                                <tr>
                                    <td>Semester</td>
                                    <td>: {{ $student->semester }}</td>
                                </tr>
                                <tr>
                                    <td>Jenis Kelamin</td>
                                    <td>: {{ $student->jenis_kelamin == 'L' ? 'Laki-laki' : 'Perempuan' }}</td>
                                </tr>
                                <tr>
                                    <td>Angkatan</td>
                                    <td>: {{ $student->angkatan }}</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="row">
                <a href="{{ url('/students') }}" class="btn btn-danger ml-3"><i class="fas fa-arrow-circle-left"></i> Kembali</a>
                
                @if (Auth::user()->role_id == 1 || Auth::user()->role_id == 2)
                <a onclick="print('{{ url('/students/print/ktm/') }}/{{ $student->id }}')" class="btn btn-white border ml-2"><i class="fas fa-print"></i> Cetak KTM</a>
                
                @elseif(Auth::user()->role_id == 3)
                <a href="{{ route('students.edit_profile', $student->id) }}" class="btn btn-white border ml-5"><i class="fas fa-user-edit"></i> Edit Profile</a>
                <a href="{{ url('/user/student/password/edit') }}" class="btn btn-white border ml-2"><i class="fas fa-key"></i> Edit Password</a>
                @endif
            </div>
        @endcard
    </div>
</div>
@endsection

@push('scripts')
    <script>
        $('.profile').parent().addClass('active');

        function print(url) {
            window.open(url, "Nota PDF", "height=675, width=1024, left=175, scrollbars=yes");
        }
    </script>
@endpush

resources/views/students/index.blade.php
@extends('layouts.master')

@section('content')
<div class="panel-header bg-primary-gradient">
    <div class="page-inner py-5">
        <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
            <div>
                <h2 class="text-white pb-2 fw-bold">Daftar Mahasiswa</h2>
            </div>
            <div class="ml-md-auto py-2 py-md-0">
                <a href="{{ route('students.create') }}" class="btn btn-white btn-sm btn-border"><i class="fas fa-plus-circle"></i> Tambah</a>
            </div>
        </div>
    </div>
</div>

<div class="page-inner mt--5">
    <div class="row mt--2">
        <div class="col-12">
            @card
                @slot('title')
                    
                @endslot

                @table
                    @slot('thead')
                        <th>No</th>
                        <th>NIM</th>
                        <th>Nama</th>
                        <th>Gender</th>
                        <th>Jurusan</th>
                        <th>Angkatan</th>
                        <th>Aksi</th>
                    @endslot
                    
                    @php $no = 1; @endphp
                    @foreach ($students as $student)
                        <tr>
                            <td width="5%">{{ $no++ }}.</td>
                            <td>{{ $student->nim }}</td>
                            <td width="25%">{{ $student->nama }}</td>
                            <td>{{ $student->jenis_kelamin == 'L' ? 'Laki-laki' : 'Perempuan' }}</td>
                            <td>
                                @foreach ($departments as $department)
                                    {{ $department->kode == $student->kode_jurusan ? $department->nama : '' }}
                                @endforeach
                            </td>
                            <td width="5%">{{ $student->angkatan }}</td>
                            <td width="5%">
                                <form method="POST" action="{{ route('students.destroy', $student->id) }}">
                                    @csrf @method('delete')
                                    <div class="form-button-action text-center">
                                        <a href="{{ route('students.edit', $student->id) }}" class="btn btn-link btn-primary" title="Edit"><i class="far fa-edit"></i></a>
                                        <button class="btn btn-link btn-danger" title="Delete" onclick="return confirm('Yakin?')"><i class="fas fa-trash-alt"></i></button>
                                        <a href="{{ route('students.show', $student->id) }}" class="btn btn-link btn-default" title="Detail"><i class="fas fa-search-plus"></i></a>
                                    </div>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                @endtable
                <div class="card-footer mt-3">
                    <a onclick="window.open('{{ url('/students/print/ktm/') }}', 'Nota PDF', 'height=675, width=1024, left=175, scrollbars=yes');" class="btn btn-primary btn-sm text-white"><i class="fas fa-print"></i> Cetak KTM</a>
                </div>
            @endcard
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
    $('.table').DataTable({
        "language": {
            "zeroRecords": "<strong>Data tidak ditemukan</strong>"
        }
    })

    $('.card-header').addClass('d-none')
</script>
@endpush

resources/views/students/print_ktm.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Cetak KTM</title>
	<link rel="stylesheet" href="{{ asset('assets/css/bootstrap.min.css') }}">

	<style>
		.card-body td {
			font-size: .8em;
		}
	</style>
</head>
<body onload="window.print()">
	<div class="container-fluid">
		<div class="row mt-3">
			<div class="col-6">
				<div class="card mb-3">
					<div class="card-header p-0" style="overflow: hidden;">
						 <img src="{{ asset('assets/img/kop.jpg') }}" alt="" width="100%">
					</div>

					<div class="row no-gutters">
						<div class="col-md-4">
							@if (file_exists(public_path().'/assets/img/uploads/'.$student->foto))
							<img src="{{ asset('assets/img/uploads/') }}/{{ $student->foto }}" alt="" class="card-img p-4">
							@else
							<img src="{{ asset('assets/img/uploads/') }}/default.png" alt="" class="card-img p-4">
							@endif
							<p class="text-center" style="font-size: .8em;"><strong>Berlaku: Selama Menjadi Mahasiswa</strong></p>
						</div>
						<div class="col-md-8">
							<div class="card-body">
								<h5 class="card-title font-weight-bold">KARTU TANDA MAHASISWA</h5>
								<table>
									<tr>
										<td width="35%">Nama</td>
										<td>: {{ $student->nama }}</td>
									</tr>
									<tr>
										<td>Tmpt/Tgl. Lahir</td>
										<td>: {{ $student->tempat_lahir }}, {{ $student->tanggal_lahir }}</td>
									</tr>
									<tr>
										<td>NIM</td>
										<td>: {{ $student->nim }}</td>
									</tr>
									<tr>
										<td>Tahun Masuk</td>
										<td>: {{ $student->angkatan }}</td>
									</tr>
									<tr>
										<td>Prodi</td>
										<td>: 
											@foreach ($departments as $department)
												{{ $department->kode == $student->kode_jurusan ? $department->nama : '' }}
											@endforeach
										</td>
									</tr>
									<tr>
										<td>Alamat</td>
										<td>: {{ $student->alamat }}</td>
									</tr>
									<tr>
										<td>Gol. Darah</td>
										<td>: -</td>
									</tr>
									<tr>
										<td>Telp/HP</td>
										<td>: {{ $student->telpon }}</td>
									</tr>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>